# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HawkBook
email: tylerwchilds@gmail.com
description: >
  HawkBook allows scholars to buy and sell textbooks with each other
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hawkbook.com" # the base hostname & protocol for your site
tagline: P2P Textbook Marketplace

# Build settings
markdown: kramdown
